// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4UrTzN6fAYxHJ6ykkEnFMW9Bu4S7R5kQ',
    appId: '1:618571096903:web:776640e0ecfbb07119a262',
    messagingSenderId: '618571096903',
    projectId: 'mobile-dzung',
    authDomain: 'mobile-dzung.firebaseapp.com',
    databaseURL: 'https://mobile-dzung-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mobile-dzung.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfEnZjtb4cfYoNlQKs_H9EZy8FwaOSF-I',
    appId: '1:618571096903:android:f78765ec5f1b06ac19a262',
    messagingSenderId: '618571096903',
    projectId: 'mobile-dzung',
    databaseURL: 'https://mobile-dzung-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mobile-dzung.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1VSjwSNVT-Tq_z5ssEMdee4hKf-vES6Y',
    appId: '1:618571096903:ios:23e62b01ddf3b6ef19a262',
    messagingSenderId: '618571096903',
    projectId: 'mobile-dzung',
    databaseURL: 'https://mobile-dzung-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mobile-dzung.appspot.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1VSjwSNVT-Tq_z5ssEMdee4hKf-vES6Y',
    appId: '1:618571096903:ios:23e62b01ddf3b6ef19a262',
    messagingSenderId: '618571096903',
    projectId: 'mobile-dzung',
    databaseURL: 'https://mobile-dzung-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mobile-dzung.appspot.com',
    iosBundleId: 'com.example.mobile',
  );
}
